[package]
name = "wasm-init-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
wasm-init = { path = "../wasm-init", features = [ "auto-init" ] }
wasm-bindgen = "0.2"
